name: Build PowerShell Module Manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - story/*

jobs:

  increment-versions:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Run increment-versions script
      run: powershell -File powershell-utility-scripts/Shared/increment-versions.ps1
        
    - name: Commit updated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Increment ModuleVersions"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      
  publish:
    needs: increment-versions
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install PowerShellGet
        run: |
          Install-Module -Name PowerShellGet -Force -AllowClobber

      - name: Publish Modules
        run: powershell-utility-scripts/Shared/rebuild-manifest.ps1
