name: Build PowerShell Module Manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - story/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install PowerShellGet
        run: |
          Install-Module -Name PowerShellGet -Force -AllowClobber

      - name: Publish Modules
        run: powershell-utility-scripts/Shared/rebuild-manifest.ps1
