name: Publish PowerShell Modules

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: PowerShell/PowerShell-Setup@v2
          
      - name: Install PowerShellGet
        run: |
          Install-Module -Name PowerShellGet -Force -AllowClobber

      - name: Publish Modules
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          $modules = @("Open-File", "Save-File", "Get-LargeTextInput", "Compare-Strings", "Search-ExcelContent")
          foreach ($module in $modules) {
            Publish-Module -Path "/powershell-utility-scripts/Shared/$module" -ApiKey $env:NUGET_KEY -Force
          }
