name: Publish Modules CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*
      - story/*

jobs:

  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install PowerShellGet
        run: |
          Install-Module -Name PowerShellGet -Force -AllowClobber

      - name: Publish Modules
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}  
        run: powershell-utility-scripts/Shared/publish.ps1
